### ISSUE TITLE
Weapon Select with more than 2 SWEPs

### ISSUE THREAD

**Issue by Tomelyr** [L7D/Catherine-HL2RP#10]
https://gfycat.com/DependentFatalBlackmamba

code for reproduction (100% sucessrate, newest CAT and this Shema):
for k,v in pairs(player.GetAll()) do v:Give("gmod_tool") end

**Comment by L7D** [comment]
So what is problem?

**Comment by fayzgolden666** [comment]
I don't really understand your issue here, could you be a bit more clear?

**Comment by Tomelyr** [comment]
Okay, fuck me sideways. i thought that the white one is the current selected one and now i realised, that is black one is it.
Sorry to bothered you
