### ISSUE TITLE
Issues with name/description and clothing

### ISSUE THREAD

**Issue by OmicronWhite** [L7D/Catherine-HL2RP#29]
1. When using clothing and changing characters then switching back the original model is used even though the clothing is worn in the inventory
![2015-07-01_00008](https://cloud.githubusercontent.com/assets/13123325/8459364/4f916f7e-2025-11e5-92d7-7574bcdadf93.jpg)
![2015-07-01_00009](https://cloud.githubusercontent.com/assets/13123325/8459363/4f8e7526-2025-11e5-8f86-6d1d49681718.jpg)
![2015-07-01_00010](https://cloud.githubusercontent.com/assets/13123325/8459366/4f974d9a-2025-11e5-91e7-32bc84736bad.jpg)
![2015-07-01_00011](https://cloud.githubusercontent.com/assets/13123325/8459365/4f92854e-2025-11e5-8e33-ed0bd837d48a.jpg)

2. When changing a character's name using /charsetname or the description, they don't update in the character menu (Though it did after a restart)
![2015-07-01_00012](https://cloud.githubusercontent.com/assets/13123325/8459393/8c13804a-2025-11e5-9a64-47018149c80c.jpg)
![cat1](https://cloud.githubusercontent.com/assets/13123325/8459400/9abc755c-2025-11e5-9978-b0a360e2c368.png)
![2015-07-01_00014](https://cloud.githubusercontent.com/assets/13123325/8459403/9f92c342-2025-11e5-9e9b-22d39a5e0576.jpg)
![2015-07-01_00016](https://cloud.githubusercontent.com/assets/13123325/8459406/a12f452c-2025-11e5-9d86-0299de608ee9.jpg)

**Comment by L7D** [comment]
What are you using clothing base or bodygroup clothing base?

**Comment by OmicronWhite** [comment]
Clothing base

**Comment by L7D** [comment]
I fixed it that

Thanks for using Catherine!
