### ISSUE TITLE
음성 명령어를 여러개 칠 수 있도록 부탁드립니다.

### ISSUE THREAD

**Issue by Sweetnut1018** [L7D/Catherine-HL2RP#46]
시민, 거기서 멈춰라! 하면 시민도 들리고 거기서 멈춰라도 들리게 해주셨으면 좋겠습니다.
그리고 기존의 예를 들어 스트라이커, 장전하라. 라고 할 경우 스트라이커. 로 끝나는 오류도 고쳐주십시오.

**Comment by L7D** [comment]
보류 처리 - 2015-10-16 PM 6:28

**Comment by L7D** [comment]
디버그 필요 - 2015-10-19 PM 12:34
