### ISSUE TITLE
진압봉 켜짐/꺼짐 제안

### ISSUE THREAD

**Issue by Sweetnut1018** [L7D/Catherine-HL2RP#52]
진압봉을 킨 상태로 내리면 킨 상태로 내려지는데
그 상태에서 다시 올리면 꺼져버리네요.
아예 내릴때도 꺼지게 하시거나 올릴 때 켜져있는 상태로 올려지도록 해주세요.

**Comment by L7D** [comment]
Fixed - 2015-10-16 PM 6:11
